// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/trips": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Create a new trip",
                "parameters": [
                    {
                        "description": "Trip details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateTripRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.TripResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/trips/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Get user's trips",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.TripResponse"
                            }
                        }
                    }
                }
            }
        },
        "/trips/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Get trip by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TripResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/trips/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Cancel a trip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancellation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CancelTripRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TripResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CancelTripRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "Changed my mind"
                }
            }
        },
        "domain.CreateTripRequest": {
            "type": "object",
            "required": [
                "dropoff_address",
                "dropoff_latitude",
                "dropoff_longitude",
                "pickup_address",
                "pickup_latitude",
                "pickup_longitude"
            ],
            "properties": {
                "dropoff_address": {
                    "type": "string",
                    "example": "Westlands"
                },
                "dropoff_latitude": {
                    "type": "number",
                    "example": -1.292066
                },
                "dropoff_longitude": {
                    "type": "number",
                    "example": 36.821945
                },
                "pickup_address": {
                    "type": "string",
                    "example": "Nairobi CBD"
                },
                "pickup_latitude": {
                    "type": "number",
                    "example": -1.286389
                },
                "pickup_longitude": {
                    "type": "number",
                    "example": 36.817223
                }
            }
        },
        "domain.DriverProfile": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "current_latitude": {
                    "type": "number"
                },
                "current_longitude": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "is_approved": {
                    "type": "boolean"
                },
                "is_online": {
                    "type": "boolean"
                },
                "license_number": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "total_trips": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "vehicle_color": {
                    "type": "string"
                },
                "vehicle_model": {
                    "type": "string"
                },
                "vehicle_plate_number": {
                    "type": "string"
                },
                "vehicle_type": {
                    "type": "string"
                }
            }
        },
        "domain.DriverWithInfo": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "driver_profile": {
                    "$ref": "#/definitions/domain.DriverProfile"
                },
                "user": {
                    "$ref": "#/definitions/domain.User"
                }
            }
        },
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request"
                },
                "message": {
                    "type": "string",
                    "example": "Detailed error message"
                }
            }
        },
        "domain.Trip": {
            "type": "object",
            "properties": {
                "actual_duration": {
                    "type": "integer"
                },
                "actual_fare": {
                    "type": "number"
                },
                "cancellation_reason": {
                    "type": "string"
                },
                "cancelled_at": {
                    "type": "string"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "distance": {
                    "type": "number"
                },
                "driver_id": {
                    "type": "string"
                },
                "dropoff_address": {
                    "type": "string"
                },
                "dropoff_latitude": {
                    "type": "number"
                },
                "dropoff_longitude": {
                    "type": "number"
                },
                "estimated_duration": {
                    "type": "integer"
                },
                "estimated_fare": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "payment_status": {
                    "type": "string"
                },
                "pickup_address": {
                    "type": "string"
                },
                "pickup_latitude": {
                    "type": "number"
                },
                "pickup_longitude": {
                    "type": "number"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "description": "pending, accepted, in_progress, completed, cancelled",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.TripResponse": {
            "type": "object",
            "properties": {
                "available_drivers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DriverWithInfo"
                    }
                },
                "trip": {
                    "$ref": "#/definitions/domain.Trip"
                }
            }
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "phone_number": {
                    "type": "string"
                },
                "profile_image_url": {
                    "type": "string"
                },
                "role": {
                    "description": "user, driver, admin",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Trip Service API",
	Description:      "Trip management and booking service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
