// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drivers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDriverProfile = `-- name: CreateDriverProfile :one
INSERT INTO driver_profiles (
    user_id,
    license_number,
    vehicle_type,
    vehicle_model,
    vehicle_color,
    vehicle_plate_number
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, license_number, vehicle_type, vehicle_model, vehicle_color, vehicle_plate_number, is_online, is_approved, rating, total_trips, current_latitude, current_longitude, created_at, updated_at
`

type CreateDriverProfileParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	LicenseNumber      string      `json:"license_number"`
	VehicleType        string      `json:"vehicle_type"`
	VehicleModel       string      `json:"vehicle_model"`
	VehicleColor       string      `json:"vehicle_color"`
	VehiclePlateNumber string      `json:"vehicle_plate_number"`
}

func (q *Queries) CreateDriverProfile(ctx context.Context, arg CreateDriverProfileParams) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, createDriverProfile,
		arg.UserID,
		arg.LicenseNumber,
		arg.VehicleType,
		arg.VehicleModel,
		arg.VehicleColor,
		arg.VehiclePlateNumber,
	)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.VehicleType,
		&i.VehicleModel,
		&i.VehicleColor,
		&i.VehiclePlateNumber,
		&i.IsOnline,
		&i.IsApproved,
		&i.Rating,
		&i.TotalTrips,
		&i.CurrentLatitude,
		&i.CurrentLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriverProfile = `-- name: GetDriverProfile :one
SELECT id, user_id, license_number, vehicle_type, vehicle_model, vehicle_color, vehicle_plate_number, is_online, is_approved, rating, total_trips, current_latitude, current_longitude, created_at, updated_at FROM driver_profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDriverProfile(ctx context.Context, id pgtype.UUID) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, getDriverProfile, id)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.VehicleType,
		&i.VehicleModel,
		&i.VehicleColor,
		&i.VehiclePlateNumber,
		&i.IsOnline,
		&i.IsApproved,
		&i.Rating,
		&i.TotalTrips,
		&i.CurrentLatitude,
		&i.CurrentLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriverProfileByUserID = `-- name: GetDriverProfileByUserID :one
SELECT id, user_id, license_number, vehicle_type, vehicle_model, vehicle_color, vehicle_plate_number, is_online, is_approved, rating, total_trips, current_latitude, current_longitude, created_at, updated_at FROM driver_profiles
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetDriverProfileByUserID(ctx context.Context, userID pgtype.UUID) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, getDriverProfileByUserID, userID)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.VehicleType,
		&i.VehicleModel,
		&i.VehicleColor,
		&i.VehiclePlateNumber,
		&i.IsOnline,
		&i.IsApproved,
		&i.Rating,
		&i.TotalTrips,
		&i.CurrentLatitude,
		&i.CurrentLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriverStats = `-- name: GetDriverStats :one
SELECT 
    total_trips,
    rating
FROM driver_profiles
WHERE user_id = $1
`

type GetDriverStatsRow struct {
	TotalTrips pgtype.Int4    `json:"total_trips"`
	Rating     pgtype.Numeric `json:"rating"`
}

func (q *Queries) GetDriverStats(ctx context.Context, userID pgtype.UUID) (GetDriverStatsRow, error) {
	row := q.db.QueryRow(ctx, getDriverStats, userID)
	var i GetDriverStatsRow
	err := row.Scan(&i.TotalTrips, &i.Rating)
	return i, err
}

const getNearbyDrivers = `-- name: GetNearbyDrivers :many
SELECT 
    dp.id,
    dp.user_id,
    dp.license_number,
    dp.vehicle_type,
    dp.vehicle_model,
    dp.vehicle_color,
    dp.vehicle_plate_number,
    dp.is_online,
    dp.is_approved,
    dp.rating,
    dp.total_trips,
    dp.current_latitude,
    dp.current_longitude,
    dp.created_at,
    dp.updated_at,
    u.full_name,
    u.phone_number,
    u.profile_image_url,
    (6371 * acos(
        cos(radians($1)) * cos(radians(dp.current_latitude)) *
        cos(radians(dp.current_longitude) - radians($2)) +
        sin(radians($1)) * sin(radians(dp.current_latitude))
    )) AS distance
FROM driver_profiles dp
JOIN users u ON dp.user_id = u.id
WHERE dp.is_online = TRUE 
    AND dp.is_approved = TRUE
    AND dp.current_latitude IS NOT NULL
    AND dp.current_longitude IS NOT NULL
    AND (6371 * acos(
        cos(radians($1)) * cos(radians(dp.current_latitude)) *
        cos(radians(dp.current_longitude) - radians($2)) +
        sin(radians($1)) * sin(radians(dp.current_latitude))
    )) < $3
ORDER BY distance
LIMIT $4
`

type GetNearbyDriversParams struct {
	Radians         float64        `json:"radians"`
	Radians_2       float64        `json:"radians_2"`
	CurrentLatitude pgtype.Numeric `json:"current_latitude"`
	Limit           int32          `json:"limit"`
}

type GetNearbyDriversRow struct {
	ID                 pgtype.UUID      `json:"id"`
	UserID             pgtype.UUID      `json:"user_id"`
	LicenseNumber      string           `json:"license_number"`
	VehicleType        string           `json:"vehicle_type"`
	VehicleModel       string           `json:"vehicle_model"`
	VehicleColor       string           `json:"vehicle_color"`
	VehiclePlateNumber string           `json:"vehicle_plate_number"`
	IsOnline           pgtype.Bool      `json:"is_online"`
	IsApproved         pgtype.Bool      `json:"is_approved"`
	Rating             pgtype.Numeric   `json:"rating"`
	TotalTrips         pgtype.Int4      `json:"total_trips"`
	CurrentLatitude    pgtype.Numeric   `json:"current_latitude"`
	CurrentLongitude   pgtype.Numeric   `json:"current_longitude"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	FullName           string           `json:"full_name"`
	PhoneNumber        string           `json:"phone_number"`
	ProfileImageUrl    pgtype.Text      `json:"profile_image_url"`
	Distance           int32            `json:"distance"`
}

func (q *Queries) GetNearbyDrivers(ctx context.Context, arg GetNearbyDriversParams) ([]GetNearbyDriversRow, error) {
	rows, err := q.db.Query(ctx, getNearbyDrivers,
		arg.Radians,
		arg.Radians_2,
		arg.CurrentLatitude,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNearbyDriversRow{}
	for rows.Next() {
		var i GetNearbyDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LicenseNumber,
			&i.VehicleType,
			&i.VehicleModel,
			&i.VehicleColor,
			&i.VehiclePlateNumber,
			&i.IsOnline,
			&i.IsApproved,
			&i.Rating,
			&i.TotalTrips,
			&i.CurrentLatitude,
			&i.CurrentLongitude,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.PhoneNumber,
			&i.ProfileImageUrl,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOnlineDrivers = `-- name: GetOnlineDrivers :many
SELECT dp.id, dp.user_id, dp.license_number, dp.vehicle_type, dp.vehicle_model, dp.vehicle_color, dp.vehicle_plate_number, dp.is_online, dp.is_approved, dp.rating, dp.total_trips, dp.current_latitude, dp.current_longitude, dp.created_at, dp.updated_at, u.full_name, u.phone_number, u.profile_image_url
FROM driver_profiles dp
JOIN users u ON dp.user_id = u.id
WHERE dp.is_online = TRUE AND dp.is_approved = TRUE
ORDER BY dp.rating DESC
LIMIT $1 OFFSET $2
`

type GetOnlineDriversParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetOnlineDriversRow struct {
	ID                 pgtype.UUID      `json:"id"`
	UserID             pgtype.UUID      `json:"user_id"`
	LicenseNumber      string           `json:"license_number"`
	VehicleType        string           `json:"vehicle_type"`
	VehicleModel       string           `json:"vehicle_model"`
	VehicleColor       string           `json:"vehicle_color"`
	VehiclePlateNumber string           `json:"vehicle_plate_number"`
	IsOnline           pgtype.Bool      `json:"is_online"`
	IsApproved         pgtype.Bool      `json:"is_approved"`
	Rating             pgtype.Numeric   `json:"rating"`
	TotalTrips         pgtype.Int4      `json:"total_trips"`
	CurrentLatitude    pgtype.Numeric   `json:"current_latitude"`
	CurrentLongitude   pgtype.Numeric   `json:"current_longitude"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	FullName           string           `json:"full_name"`
	PhoneNumber        string           `json:"phone_number"`
	ProfileImageUrl    pgtype.Text      `json:"profile_image_url"`
}

func (q *Queries) GetOnlineDrivers(ctx context.Context, arg GetOnlineDriversParams) ([]GetOnlineDriversRow, error) {
	rows, err := q.db.Query(ctx, getOnlineDrivers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOnlineDriversRow{}
	for rows.Next() {
		var i GetOnlineDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LicenseNumber,
			&i.VehicleType,
			&i.VehicleModel,
			&i.VehicleColor,
			&i.VehiclePlateNumber,
			&i.IsOnline,
			&i.IsApproved,
			&i.Rating,
			&i.TotalTrips,
			&i.CurrentLatitude,
			&i.CurrentLongitude,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.PhoneNumber,
			&i.ProfileImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriverLocation = `-- name: UpdateDriverLocation :exec
UPDATE driver_profiles
SET 
    current_latitude = $2,
    current_longitude = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateDriverLocationParams struct {
	UserID           pgtype.UUID    `json:"user_id"`
	CurrentLatitude  pgtype.Numeric `json:"current_latitude"`
	CurrentLongitude pgtype.Numeric `json:"current_longitude"`
}

func (q *Queries) UpdateDriverLocation(ctx context.Context, arg UpdateDriverLocationParams) error {
	_, err := q.db.Exec(ctx, updateDriverLocation, arg.UserID, arg.CurrentLatitude, arg.CurrentLongitude)
	return err
}

const updateDriverProfile = `-- name: UpdateDriverProfile :one
UPDATE driver_profiles
SET
    license_number = COALESCE($1, license_number),
    vehicle_type = COALESCE($2, vehicle_type),
    vehicle_model = COALESCE($3, vehicle_model),
    vehicle_color = COALESCE($4, vehicle_color),
    vehicle_plate_number = COALESCE($5, vehicle_plate_number),
    is_approved = COALESCE($6, is_approved),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, user_id, license_number, vehicle_type, vehicle_model, vehicle_color, vehicle_plate_number, is_online, is_approved, rating, total_trips, current_latitude, current_longitude, created_at, updated_at
`

type UpdateDriverProfileParams struct {
	LicenseNumber      pgtype.Text `json:"license_number"`
	VehicleType        pgtype.Text `json:"vehicle_type"`
	VehicleModel       pgtype.Text `json:"vehicle_model"`
	VehicleColor       pgtype.Text `json:"vehicle_color"`
	VehiclePlateNumber pgtype.Text `json:"vehicle_plate_number"`
	IsApproved         pgtype.Bool `json:"is_approved"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDriverProfile(ctx context.Context, arg UpdateDriverProfileParams) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, updateDriverProfile,
		arg.LicenseNumber,
		arg.VehicleType,
		arg.VehicleModel,
		arg.VehicleColor,
		arg.VehiclePlateNumber,
		arg.IsApproved,
		arg.ID,
	)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.VehicleType,
		&i.VehicleModel,
		&i.VehicleColor,
		&i.VehiclePlateNumber,
		&i.IsOnline,
		&i.IsApproved,
		&i.Rating,
		&i.TotalTrips,
		&i.CurrentLatitude,
		&i.CurrentLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDriverRating = `-- name: UpdateDriverRating :exec
UPDATE driver_profiles
SET rating = $2, total_trips = $3, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateDriverRatingParams struct {
	UserID     pgtype.UUID    `json:"user_id"`
	Rating     pgtype.Numeric `json:"rating"`
	TotalTrips pgtype.Int4    `json:"total_trips"`
}

func (q *Queries) UpdateDriverRating(ctx context.Context, arg UpdateDriverRatingParams) error {
	_, err := q.db.Exec(ctx, updateDriverRating, arg.UserID, arg.Rating, arg.TotalTrips)
	return err
}

const updateDriverStatus = `-- name: UpdateDriverStatus :exec
UPDATE driver_profiles
SET is_online = $2, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateDriverStatusParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	IsOnline pgtype.Bool `json:"is_online"`
}

func (q *Queries) UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) error {
	_, err := q.db.Exec(ctx, updateDriverStatus, arg.UserID, arg.IsOnline)
	return err
}
