// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDriverProfile(ctx context.Context, arg CreateDriverProfileParams) (DriverProfile, error)
	GetDriverProfile(ctx context.Context, id pgtype.UUID) (DriverProfile, error)
	GetDriverProfileByUserID(ctx context.Context, userID pgtype.UUID) (DriverProfile, error)
	GetDriverStats(ctx context.Context, userID pgtype.UUID) (GetDriverStatsRow, error)
	GetNearbyDrivers(ctx context.Context, arg GetNearbyDriversParams) ([]GetNearbyDriversRow, error)
	GetOnlineDrivers(ctx context.Context, arg GetOnlineDriversParams) ([]GetOnlineDriversRow, error)
	UpdateDriverLocation(ctx context.Context, arg UpdateDriverLocationParams) error
	UpdateDriverProfile(ctx context.Context, arg UpdateDriverProfileParams) (DriverProfile, error)
	UpdateDriverRating(ctx context.Context, arg UpdateDriverRatingParams) error
	UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) error
}

var _ Querier = (*Queries)(nil)
