// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignDriverToTrip(ctx context.Context, arg AssignDriverToTripParams) error
	CancelTrip(ctx context.Context, arg CancelTripParams) error
	CompleteTrip(ctx context.Context, arg CompleteTripParams) error
	CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error)
	GetActiveTrip(ctx context.Context, userID pgtype.UUID) (Trip, error)
	GetDriverActiveTrip(ctx context.Context, driverID pgtype.UUID) (Trip, error)
	GetDriverTrips(ctx context.Context, arg GetDriverTripsParams) ([]Trip, error)
	GetPendingTrips(ctx context.Context, arg GetPendingTripsParams) ([]GetPendingTripsRow, error)
	GetTrip(ctx context.Context, id pgtype.UUID) (Trip, error)
	GetTripWithDetails(ctx context.Context, id pgtype.UUID) (GetTripWithDetailsRow, error)
	GetUserTrips(ctx context.Context, arg GetUserTripsParams) ([]Trip, error)
	StartTrip(ctx context.Context, id pgtype.UUID) error
	UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) error
}

var _ Querier = (*Queries)(nil)
