// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRating(ctx context.Context, arg CreateRatingParams) (Rating, error)
	DeleteRating(ctx context.Context, id pgtype.UUID) error
	GetAverageRating(ctx context.Context, ratedID pgtype.UUID) (GetAverageRatingRow, error)
	GetRating(ctx context.Context, id pgtype.UUID) (Rating, error)
	GetRatingByTripAndRater(ctx context.Context, arg GetRatingByTripAndRaterParams) (Rating, error)
	GetUserRatings(ctx context.Context, arg GetUserRatingsParams) ([]GetUserRatingsRow, error)
	UpdateRating(ctx context.Context, arg UpdateRatingParams) (Rating, error)
}

var _ Querier = (*Queries)(nil)
