// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DriverProfile struct {
	ID                 pgtype.UUID      `json:"id"`
	UserID             pgtype.UUID      `json:"user_id"`
	LicenseNumber      string           `json:"license_number"`
	VehicleType        string           `json:"vehicle_type"`
	VehicleModel       string           `json:"vehicle_model"`
	VehicleColor       string           `json:"vehicle_color"`
	VehiclePlateNumber string           `json:"vehicle_plate_number"`
	IsOnline           pgtype.Bool      `json:"is_online"`
	IsApproved         pgtype.Bool      `json:"is_approved"`
	Rating             pgtype.Numeric   `json:"rating"`
	TotalTrips         pgtype.Int4      `json:"total_trips"`
	CurrentLatitude    pgtype.Numeric   `json:"current_latitude"`
	CurrentLongitude   pgtype.Numeric   `json:"current_longitude"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type Rating struct {
	ID        pgtype.UUID      `json:"id"`
	TripID    pgtype.UUID      `json:"trip_id"`
	RaterID   pgtype.UUID      `json:"rater_id"`
	RatedID   pgtype.UUID      `json:"rated_id"`
	Rating    int32            `json:"rating"`
	Feedback  pgtype.Text      `json:"feedback"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type RideRequest struct {
	ID          pgtype.UUID      `json:"id"`
	TripID      pgtype.UUID      `json:"trip_id"`
	DriverID    pgtype.UUID      `json:"driver_id"`
	Status      string           `json:"status"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	RespondedAt pgtype.Timestamp `json:"responded_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Trip struct {
	ID                 pgtype.UUID      `json:"id"`
	UserID             pgtype.UUID      `json:"user_id"`
	DriverID           pgtype.UUID      `json:"driver_id"`
	PickupLatitude     pgtype.Numeric   `json:"pickup_latitude"`
	PickupLongitude    pgtype.Numeric   `json:"pickup_longitude"`
	PickupAddress      string           `json:"pickup_address"`
	DropoffLatitude    pgtype.Numeric   `json:"dropoff_latitude"`
	DropoffLongitude   pgtype.Numeric   `json:"dropoff_longitude"`
	DropoffAddress     string           `json:"dropoff_address"`
	EstimatedFare      pgtype.Numeric   `json:"estimated_fare"`
	ActualFare         pgtype.Numeric   `json:"actual_fare"`
	EstimatedDuration  pgtype.Int4      `json:"estimated_duration"`
	ActualDuration     pgtype.Int4      `json:"actual_duration"`
	Distance           pgtype.Numeric   `json:"distance"`
	Status             string           `json:"status"`
	PaymentStatus      pgtype.Text      `json:"payment_status"`
	PaymentMethod      pgtype.Text      `json:"payment_method"`
	StartedAt          pgtype.Timestamp `json:"started_at"`
	CompletedAt        pgtype.Timestamp `json:"completed_at"`
	CancelledAt        pgtype.Timestamp `json:"cancelled_at"`
	CancellationReason pgtype.Text      `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID               pgtype.UUID      `json:"id"`
	PhoneNumber      string           `json:"phone_number"`
	Email            pgtype.Text      `json:"email"`
	PasswordHash     string           `json:"password_hash"`
	FullName         string           `json:"full_name"`
	Role             string           `json:"role"`
	ProfileImageUrl  pgtype.Text      `json:"profile_image_url"`
	IsVerified       pgtype.Bool      `json:"is_verified"`
	IsActive         pgtype.Bool      `json:"is_active"`
	ResetToken       pgtype.Text      `json:"reset_token"`
	ResetTokenExpiry pgtype.Timestamp `json:"reset_token_expiry"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}
