// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearResetToken = `-- name: ClearResetToken :exec
UPDATE users
SET reset_token = NULL, reset_token_expiry = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ClearResetToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearResetToken, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    phone_number,
    email,
    password_hash,
    full_name,
    role
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, phone_number, email, password_hash, full_name, role, profile_image_url, is_verified, is_active, reset_token, reset_token_expiry, created_at, updated_at
`

type CreateUserParams struct {
	PhoneNumber  string      `json:"phone_number"`
	Email        pgtype.Text `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.PhoneNumber,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, phone_number, email, password_hash, full_name, role, profile_image_url, is_verified, is_active, reset_token, reset_token_expiry, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone_number, email, password_hash, full_name, role, profile_image_url, is_verified, is_active, reset_token, reset_token_expiry, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone_number, email, password_hash, full_name, role, profile_image_url, is_verified, is_active, reset_token, reset_token_expiry, created_at, updated_at FROM users
WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, phone_number, email, password_hash, full_name, role, profile_image_url, is_verified, is_active, reset_token, reset_token_expiry, created_at, updated_at FROM users
WHERE reset_token = $1 AND reset_token_expiry > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetUserByResetToken(ctx context.Context, resetToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByResetToken, resetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, phone_number, email, password_hash, full_name, role, profile_image_url, is_verified, is_active, reset_token, reset_token_expiry, created_at, updated_at FROM users
WHERE role = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	Role   string `json:"role"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.ProfileImageUrl,
			&i.IsVerified,
			&i.IsActive,
			&i.ResetToken,
			&i.ResetTokenExpiry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResetToken = `-- name: SetResetToken :exec
UPDATE users
SET reset_token = $2, reset_token_expiry = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type SetResetTokenParams struct {
	ID               pgtype.UUID      `json:"id"`
	ResetToken       pgtype.Text      `json:"reset_token"`
	ResetTokenExpiry pgtype.Timestamp `json:"reset_token_expiry"`
}

func (q *Queries) SetResetToken(ctx context.Context, arg SetResetTokenParams) error {
	_, err := q.db.Exec(ctx, setResetToken, arg.ID, arg.ResetToken, arg.ResetTokenExpiry)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = COALESCE($1, email),
    full_name = COALESCE($2, full_name),
    profile_image_url = COALESCE($3, profile_image_url),
    is_verified = COALESCE($4, is_verified),
    is_active = COALESCE($5, is_active),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $6
RETURNING id, phone_number, email, password_hash, full_name, role, profile_image_url, is_verified, is_active, reset_token, reset_token_expiry, created_at, updated_at
`

type UpdateUserParams struct {
	Email           pgtype.Text `json:"email"`
	FullName        pgtype.Text `json:"full_name"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
	IsVerified      pgtype.Bool `json:"is_verified"`
	IsActive        pgtype.Bool `json:"is_active"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.FullName,
		arg.ProfileImageUrl,
		arg.IsVerified,
		arg.IsActive,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
